env:
    - CODECOV_TOKEN="245d5a90-4b83-4f7d-b128-e529ee0a7a6f"
language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
before_install:
    - pip install -U pip
install:
    - pip install -r requirements.txt
    - pip install codecov
script:
    - coverage run --source=metronome -m unittest -v
    - coverage report -im
after_success:
    - codecov