language: python
python:
    - "3.6"
    - "3.7"
    - "3.8"
before_install:
    - pip install -U pip
install:
    - pip install -r requirements.txt
    - pip install coveralls
script:
    - coverage run --omit tests/* -m unittest -v
after_script:
    - coveralls